### ISSUE TITLE
Communication stops in bad network environment

### ISSUE THREAD

**Issue by firesurfer** [ros2/rmw_opensplice#115]
When testing with my demo program ( https://github.com/firesurfer/ros2_components_demo ) 
with opensplice dds the communication stops if I run the demo_parameter_service on another computer connected via wireless lan. 
Both programs (demo_parameter_server and demo_server which uses the parameter service) 
state a "Missed heartbeat for node - heartbeat id " warning after publishing about 39 of 100 parameter sets. 

My dds settings are:
rmw_qos_profile_sensor_data;
without any changes to the profile.

**Comment by dhood** [comment]
we'll close this under the assumption that opensplice 6.7 addresses the issue but can reopen it if that's not the case
