### ISSUE TITLE
Thread and memory leaks

### ISSUE THREAD

**Issue by gerkey** [ros2/rmw_opensplice#145]
As originally identified during the investigation of #99, any program that uses OpenSplice appears to leak memory and often threads, at least on Linux. The leakage is most pronounced when repeatedly creating and deleting entities (such as domain participants).

A trivial OpenSplice program that demonstrates the problem can be found here: https://github.com/PrismTech/opensplice/issues/27. Until that problem is resolved, there's not much point in investigating higher-level resource leakage. We can leave this issue as a placeholder for such problems.

**Comment by dhood** [comment]
we'll close this under the assumption that opensplice 6.7 addresses the issue but can reopen it if that's not the case
