### ISSUE TITLE
try using "on matched" for service topics to improve wait_for_service

### ISSUE THREAD

**Issue by wjwwood** [ros2/rmw_opensplice#147]
See: https://github.com/ros2/ros2/issues/215#issuecomment-226589984

**Comment by dirk-thomas** [comment]
Can this be closed? It seems to be addressed by #185.

**Comment by dirk-thomas** [comment]
I will close this for now assuming it has been addressed by the referenced PR. Please feel free to comment here and reopen the ticket if that is not the case.
