### ISSUE TITLE
add support for local graph changes

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rmw_opensplice#155]
`rmw_destroy_client` and `rmw_destroy_service` should notify the graph of the suppression

**Comment by wjwwood** [comment]
I don't think opensplice is missing this feature. Unless I'm mistaken it reports local changes to topics already and so services should work as well.

**Comment by mikaelarguedas** [comment]
I wanted to get your feedback on this because I wasn't sure if opensplice needed the node handle to do it or if it was already done under the hood. In this case we can just keep these variables unused to match the rmw API and close this issue.

**Comment by wjwwood** [comment]
I believe OpenSplice just doesn't need them.
