### ISSUE TITLE
Kick off CI build on master

### ISSUE THREAD

**Issue by michielb-prismtech** [ros2/rmw_opensplice#186]
Could someone kick off a CI build on master, so that we can see the latest state. Expecting an OpenSplice update soon would like to be able to check for diffs.

Thanks

**Comment by wjwwood** [comment]
Here's master: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3079)](http://ci.ros2.org/job/ci_linux/3079/)

**Comment by michielb-prismtech** [comment]
Thank you
