### ISSUE TITLE
implement `rmw_service_names_and_types`

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rmw_opensplice#199]
Currently the rmw function `rmw_service_names_and_types` is not implemented (see https://github.com/ros2/rmw_opensplice/blob/ee19bdf5957ff1ac7384604583d43feacae2e6b5/rmw_opensplice_cpp/src/rmw_service_names_and_types.cpp#L34).

This is necessary to support the `ros1_bridge`.

**Comment by mikaelarguedas** [comment]
Note: A test for this could be added to the ros2cli test suite to catch these errors in regular ci and not only on the packaging job

**Comment by michielb-prismtech** [comment]
Working on the implementation, can takers for the testcase?

**Comment by dirk-thomas** [comment]
> can takers for the testcase?

Can you please clarify the question.

You can call `ros2 service list` on the command line to try the API. Maybe run a server / client at the same time.

**Comment by michielb-prismtech** [comment]
>Can you please clarify the question.
more of a response to 
>Note: A test for this could be added to the ros2cli test suite to catch these errors in regular ci and not only on the packaging job

**Comment by dirk-thomas** [comment]
@michielb-prismtech You don't have to worry about the test coverage for this. If it works for you with the command line tool that would be great.

**Comment by wjwwood** [comment]
For anyone who is interested, the tests for this function's "sister" function are here:

https://github.com/ros2/rcl/blob/master/rcl/test/rcl/test_graph.cpp#L122-L158

Probably could be duplicated and slightly modified for coverage of this function.

**Comment by dirk-thomas** [comment]
We might have to release Beta 3 without this change - depending on the time frame. We plan to announce the release tomorrow.

**Comment by dirk-thomas** [comment]
Addressed by #200.
