### ISSUE TITLE
publishing or subscribing with builtin_interfaces Time (and likely Duration) fails with an assertion

### ISSUE THREAD

**Issue by tfoote** [ros2/rmw_opensplice#216]
rmw_opensplice special cases builtin_interfaces, like [here](https://github.com/ros2/rmw_opensplice/blob/master/rosidl_typesupport_opensplice_c/cmake/rosidl_typesupport_opensplice_c_generate_interfaces.cmake#L24)

However this is causing failures as observed testing ros2/rclcpp#407

The underlying problem is that get_message_type_support_handle is returning null for builtin_interfaces datatypes. 
```
  auto time_typesupport_handle = rosidl_typesupport_cpp::get_message_type_support_handle<builtin_interfaces::msg::Time>();
  std::cout << "Time typesupport handle is " << time_typesupport_handle << std::endl;

  auto parameter_typesupport_handle = rosidl_typesupport_cpp::get_message_type_support_handle<rcl_interfaces::msg::Parameter>();
  std::cout << "Parameter typesupport handle is " << parameter_typesupport_handle << std::endl;
```
Result:
```
Time typesupport handle is 0
Parameter typesupport handle is 0x7ffff60912e0
```

This method is used directly in the rclcpp [subscription constructor](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/subscription.hpp#L160).
Which causes the constructor to fail.

This also is an issue for publishing [here](https://github.com/ros2/rclcpp/blob/master/rclcpp/include/rclcpp/publisher.hpp#L176)

**Comment by dirk-thomas** [comment]
The problem is that the function providing the type support pointer return `0` for the custom types duration and time (see e.g. https://github.com/ros2/rmw_opensplice/blob/eeffe49beb7a41aca800ffa156b9ecdf02b83747/rosidl_typesupport_opensplice_cpp/resource/time__type_support.cpp#L55-L59).
