### ISSUE TITLE
Talker demo node fails when run with rmw_opensplice_cpp

### ISSUE THREAD

**Issue by mkhansen-intel** [ros2/rmw_opensplice#283]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - master branch 2ef6b61710f7095caad7cb5971bc6348fc1869bf
- DDS implementation:
  - rmw_opensplice
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Follow directions for building ROS2 from source, and working with multiple rmw implementations: https://index.ros.org//doc/ros2/Tutorials/Working-with-multiple-RMW-implementations/
```
mkhansen@mkhansen-desk:~/ros2_dev/ros2_ws/src/ros2/rmw_opensplice$ export RMW_IMPLEMENTATION=rmw_opensplice_cpp
mkhansen@mkhansen-desk:~/ros2_dev/ros2_ws/src/ros2/rmw_opensplice$ ros2 run demo_nodes_cpp talker
```

#### Expected behavior
"Hello World " should be printing on the screen

#### Actual behavior
```
========================================================================================
Context     : DDS::DomainParticipantFactory::create_participant
Date        : 2019-09-12T13:29:32-0700
Node        : mkhansen-desk
Process     : talker <6636>
Thread      : main thread 7f5596336f40
Internals   : DomainParticipantFactory.cpp/324/6.9.190705OSS///-1
----------------------------------------------------------------------------------------
Report      : Unable to connect to domain id = 7.
              The most common causes of this error are an incorrect configuration file or
              that OpenSpliceDDS is not running (when using shared memory mode).
Internals   : u_participantNew/u_participant.c/234/774/1568320172.795758339
----------------------------------------------------------------------------------------
Report      : Failed to initialize domain configuration for domain 7
Internals   : u__domainOpen/u_domain.c/1485/774/1568320172.795762902
----------------------------------------------------------------------------------------
Report      : Invalid URI specified: "file:///share/opensplice_cmake_module/config/ros_ospl.xml".
Internals   : user::u_domain::GetDomainConfig/u_domain.c/241/774/1568320172.795765966

>>> [rcutils|error_handling.c:107] rcutils_set_error_state()
This error state is being overwritten:

  'failed to create domain participant, at /home/mkhansen/ros2_dev/ros2_ws/src/ros2/rmw_opensplice/rmw_opensplice_cpp/src/rmw_node.cpp:162, at /home/mkhansen/ros2_dev/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:326'

with this new error message:

  'rcl node's rmw handle is invalid, at /home/mkhansen/ros2_dev/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:464'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [rcl]: Failed to fini publisher for node: 1
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to initialize rcl node: rcl node's rmw handle is invalid, at /home/mkhansen/ros2_dev/ros2_ws/src/ros2/rcl/rcl/src/rcl/node.c:464
```
#### Additional information
This is new behavior, I've run opensplice successfully in the past on this machine. Most recently was 8/29/19. Also I asked another member of the team to try the same demo and he got the same error.

**Comment by dirk-thomas** [comment]
The nightly CI seems to pass the `talker` / `listener` tests with OpenSplice just fine: http://build.ros2.org/view/Eci/job/Eci__nightly-opensplice_ubuntu_bionic_amd64/73/testReport/demo_nodes_cpp/TestExecutablesTutorial/test_processes_output_6/

So I would suggest to double check your environment.

**Comment by jacobperron** [comment]
I'm getting the same error on my machine. It looks like `OSPL_URI` is not set correctly, it is pointing to a relative path that cannot be resolved. From the report:

```
Report      : Invalid URI specified: "file:///share/opensplice_cmake_module/config/ros_ospl.xml".
```

If I manually set `OSPL_URI` to the absolute path of `ros_ospl.xml` in my install directory, then the demo works.

**Comment by dirk-thomas** [comment]
That looks like the variable `AMENT_CURRENT_PREFIX` was empty when the script was sourced: https://github.com/ros2/rosidl_typesupport_opensplice/blob/edfffecd83a590e965d78396f68e3d7ff54a9ec3/opensplice_cmake_module/env_hook/opensplice.sh.in#L37

That is likely related to the faster environment setup which bypasses a lot of the ament logic.

Adding the same fallback logic as in https://github.com/ament/ament_package/blob/6c8acd25498d2674e7ad9d316b35d112ae1ab8c1/ament_package/template/package_level/local_setup.sh.in#L6-L13 should resolve it. Not sure if there is a nicer way though...

**Comment by mkhansen-intel** [comment]
So how do I fix this?

**Comment by jacobperron** [comment]
@mkhansen-intel Please try https://github.com/ros2/rosidl_typesupport_opensplice/pull/42 and let me know if it fixes the issue for you too.
