### ISSUE TITLE
Memory Leak when running many nodes

### ISSUE THREAD

**Issue by fabmene** [ros2/rmw_opensplice#302]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Binaries
- DDS implementation:
  - OpenSplice
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
1. Implement bare-bones node:
```
#include <rclcpp/rclcpp.hpp>

class MinimalNode : public rclcpp ::Node
{

public:
  MinimalNode() : rclcpp::Node("minimal") { RCLCPP_INFO(this->get_logger(), "Hello"); }
};

int main(int argc, char** argv)
{
  rclcpp::init(argc, argv);
  std::setvbuf(stdout, NULL, _IONBF, BUFSIZ);

  rclcpp::Node::SharedPtr node = std::make_shared<MinimalNode>();
  rclcpp::spin(node);

  return 0;
}
```
2. Start 200 of those

#### Expected behavior
Nodes start normally.

#### Actual behavior
Following error is displayed:
```
    [min_node-22] Report      : API_INFO
    [min_node-22] Date        : 2020-02-21T14:33:49+0100
    [min_node-22] Description : The number of samples '5000' has surpassed the warning level of '5000' samples.
    [min_node-22] Node        : <hostname>
    [min_node-22] Process     : min_node <22398>
    [min_node-22] Thread      : dq.builtins 7f5ec5269700
    [min_node-22] Internals   : 6.9.190705OSS///v_checkMaxSamplesWarningLevel/v_kernel.c/1940/769 /1582292029.991222504/13
```
Siginificant memory leak occurs.

#### Additional information
I am not sure whether or how the memory leak is connected to the error message, but I am only seeing both together. Starting 50 MinimalNodes produces neither the error, nor the memleak, starting 100 produces both.

**Comment by clalancette** [comment]
Closing since we no longer support OpenSplice in any active ROS 2 distribution.
