### ISSUE TITLE
Crash when subscribing to a single topic with multiple types

### ISSUE THREAD

**Issue by pjreed** [ros2/rmw_opensplice#304]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Linux 18.04
- Installation type:
  - ROS Eloquent, from binaries
- Version or commit hash:
  - 0.8.1-1bionic.20200121.221722
- DDS implementation:
  - OpenSplice
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

This issue happens when a single node subscribes to a topic multiple times and each subscriber has a different message type.

It's simple to reproduce this with rviz:

```
. /opt/ros/eloquent/setup.bash
export RMW_IMPLEMENTATION=rmw_opensplice_cpp
ros2 run rviz2 rviz2
```

1. Click Add / Pose
2. Click Add / Marker
3. Change the Pose plugin's topic to `/test`
4. Change the Marker plugin's topic to `/test`
5. rviz will crash

#### Expected behavior

The program should subscribe to the topic without crashing.  Each subscriber callback should receive messages published to that topic for the type they expect.  Note that FastRTPS behaves correctly.

#### Actual behavior

The program crashes as soon as the second `create_subscription` call is made.  Furthermore, it does not seem like it is throwing an exception; I tested this this my making my own program that subscribed to a topic multiple times, and I was unable to catch an exception, it appeared as though the program crashed due to `SIGABRT` being raised.

#### Additional information

This bug also exists with the binary version in ROS Dashing.

Console output from an example rviz session:

```
========================================================================================
Report      : WARNING
Date        : 2020-03-09T15:39:49-0500
Description : using network interface enp21s0 (x.x.x.x) selected arbitrarily from: enp21s0, docker0

Node        : hostname
Process     : rviz2 <17224>
Thread      : ddsi2 7f6a0e10d700
Internals   : 6.9.190705OSS///ddsi2/q_nwif.c/989/0/1583786389.159834517/230
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: Stereo is NOT SUPPORTED
========================================================================================
Context     : DDS::OpenSplice::DomainParticipant::create_topic
Date        : 2020-03-09T15:41:09-0500
Node        : hostname
Process     : rviz2 <17224>
Thread      : main thread 7f6a2ccc5f80
Internals   : DomainParticipant.cpp/818/6.9.190705OSS///230
----------------------------------------------------------------------------------------
Report      : Error: Could not create Topic 'rt/test'.
Internals   : DDS::OpenSplice::DomainParticipant::nlReq_createTopic/DomainParticipant.cpp/2869/1/1583786469.171228774
----------------------------------------------------------------------------------------
Report      : Create kernel entity failed. For Topic: <rt/test>
Internals   : u_topicNew/u_topic.c/192/772/1583786469.171244475
----------------------------------------------------------------------------------------
Report      : Precondition not met: Create Topic "rt/test" failed: type <visualization_msgs::msg::dds_::Marker_> differs existing type <geometry_msgs::msg::dds_::PoseStamped_>.
Internals   : v_topicNew/v_topicImpl.c/395/779/1583786469.171257663
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  could not create subscription: failed to create topic, at /tmp/binarydeb/ros-eloquent-rmw-opensplice-cpp-0.8.1/src/rmw_subscription.cpp:202, at /tmp/binarydeb/ros-eloquent-rcl-0.8.4/src/rcl/subscription.c:168
```

**Comment by clalancette** [comment]
Closing since we no longer support OpenSplice in any active ROS 2 distribution.
