### ISSUE TITLE
foxy debs unavailable 

### ISSUE THREAD

**Issue by dawonn-haval** [ros2/rmw_opensplice#305]
# Bug report
It appears that debs are not available for foxy on ubuntu 20.04.

**Required Info:**

- Operating System:
Ubuntu 20.04
- Installation type:
Binary
- Version or commit hash:
N/A
- DDS implementation:
 open_splice
- Client library (if applicable):
 N/A

#### Steps to reproduce issue
sudo apt install ros-foxy-rmw-opensplice-cpp 

#### Expected behavior
It should install

#### Actual behavior
package not found

#### Additional information
I don't see a foxy branch on git, and no commits since January. Is this project still active?

**Comment by clalancette** [comment]
No, OpenSplice functionality was removed in Foxy.  Please see https://www.ros.org/reps/rep-2000.html#foxy-fitzroy-may-2020-may-2023 for the list of supported middlewares in Foxy.
